version: '3.8'

services:
  mongoserver:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: ZeDeliveryMongo2021
    ports:
      - "27017:27017"
    volumes:
      - ./data/MongoDB:/data/db 
    command: mongod --quiet --logpath /dev/null 
    networks:
      - mongoserver-network

  server:
    build: .
    ports:
      - "3000:3000" 
    depends_on:
      - mongoserver
    environment: 
      MONGO_HOST: mongoserver
      MONGO_PORT: 27017
      MONGO_DATABASE: admin
      MONGO_USERNAME: mongoUser
      MONGO_PASSWORD: ZeDeliveryMongo2021
      APP_PORT: 3000
    networks:
      - mongoserver-network  
    # volumes:
    #   - ./data/logs:/usr/app/logs   
networks: 
    mongoserver-network:
      driver: bridge