version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: ZeDeliveryMongo@2021!
      MONGO_INITDB_DATABASE: partners
    ports:
      - "27017:27017"
    volumes:
      - ./data/MongoDB:/data/db 
  server:
    build: .
    ports:
      - "3000:3000" 
    depends_on: 
      - redis
      - mongo
    environment: 
      MONGO_HOST: 'localhost'
      MONGO_PORT: '27017'
      MONGO_DATABASE: 'partners'
      MONGO_USERNAME: 'mongoUser'
      MONGO_PASSWORD: 'ZeDeliveryMongo@2021!'
      APP_PORT: 3000
    
