openapi: 3.0.0
info:
  title: ZE-BACKEND-CHALLENGE 
  version: 1.0.0
  description: "Documentation of ze-backend-challenge"
  license:
    name: MIT
    url: 'https://spdx.org/licenses/MIT.html'
  contact:
    name: Leandro Almeida
    email: leandro_almeida@id.uff.br
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /pdv: 
    post:
      summary: "Insert new PDV"
      description: "This route have the responsability do insert new PDV"
      requestBody:
          content: 
            aplication/json:
              schema: 
                $ref: "#/components/schemas/partnerRequest"
      responses:
        "201":
          description: "Partner Created Successfully!" 
          content: 
            aplication/json:
              schema: 
                  message:
                    type: string                
                  $ref: "#/components/schemas/partnerResult"
        "409":
          description: "Partner Created Fail!" 
          content: 
            aplication/json:
              schema: 
                  message:
                    type: string                
                  $ref: "#/components/schemas/partnerResult"         



                
components:
  schemas:
    partnerRequest:
      type: "object"
      properties:
        pdv: 
           $ref: "#/components/schemas/partner"           
            

    partnerResult:
      nullable: true
      type: "object"
      properties:
        pdv:
          $ref: "#/components/schemas/partner" 
        message:
          type: string
                  

    partner: 
      type:  "object"
      properties:
        coverageArea:  
          $ref: "#/components/schemas/MultiPolygon"
        id: 
          type: string
        tradingName: 
           type:  string
        ownerName:  
           type: string
        document:  
           type: string
        address: 
          $ref: "#/components/schemas/Point"

    Point:
      type: "object"
      properties:
        coordinates: 
          type: array
          items:
            type: array
            items:
              type: integer
            minItems: 2
            maxItems: 2  
        type: 
          type: 
              string

    MultiPolygon:
      type: "object"
      properties:
        coordinates: 
          type: array 
          items:
            type: array
            items:
              type: array
              items:
                type: array
                items:
                  type: integer
                minItems: 2 
              minItems: 3
            minItems: 1      
          minItems: 1       
        type: 
          type: 
            string
